import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Inter, Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { NextThemeProvider } from "@/components/ThemeProvider";
import { Navigation } from "@/components/Navigation";
import { ThemeProvider } from "next-themes";
import AuthProvider from "@/components/AuthProvider";
import { UserInfoProvider } from "@/contexts/UserInfoContext";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});
const dmSansHeading = DM_Sans({subsets:['latin'],variable:'--font-heading'});
const raleway = Raleway({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", raleway.variable, dmSansHeading.variable)}
      suppressHydrationWarning
    >
      {/* className="dark" 추가하면 다크모드 적용 */}
      <body className="dark min-h-full flex flex-col" suppressHydrationWarning>
        {/* <NextThemeProvider */}
        <ThemeProvider
          attribute="class" // 테마를 <html> 태그의 class 속성으로 적용 - tailwind방식  (dark, light 등)
          defaultTheme="system"
          enableSystem // 브라우저/OS의 다크모드 설정을 감지해서 테마 변경 허용
          disableTransitionOnChange // 테마 전환 시 CSS transition 비활성화로 깜빡임 없이 즉시 변경 - 자식에게 transition이 있어도 무시
        >
          <AuthProvider>
            {/* favorites 추가 */}
            <UserInfoProvider>
              <Navigation />
              {children}
            </UserInfoProvider>
          </AuthProvider>
        </ThemeProvider>
        {/* </NextThemeProvider> */}
      </body>
    </html>
  );
}
